airtrail_image: "luis25franca/airtrail:v3"

# Replica Configuration for Benchmarking
initial_replicas: 1  # Set this to desired replica count for testing

# Horizontal Pod Autoscaler Configuration
hpa_enabled: true  # Set to false to disable HPA during benchmarking
hpa_min_replicas: 2
hpa_max_replicas: 5
hpa_cpu_target: 60

# Resource Requests and Limits
cpu_request: "100m"
memory_request: "256Mi"
cpu_limit: "500m" #unused
memory_limit: "512Mi" # unused  
