apiVersion: v1
kind: Service
metadata:
  name: "{{ db_host }}"
  labels:
    app: postgres
    tier: database
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - targetPort: 5432 # port that containers are listening on
      port: 5432 # port number exposed internally in the cluster