apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jmeter-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  {% if pvc_storage_class is defined and pvc_storage_class | length > 0 %}
  storageClassName: "{{ pvc_storage_class }}"
  {% endif %}