apiVersion: batch/v1
kind: Job
metadata:
  name: jmeter-airtrail-test
  namespace: default
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: jmeter
        image: justb4/jmeter:latest
        command: ["jmeter"]
        args:
          - "-n"
          - "-t"
          - "/tests/airtrail-test.jmx"
          - "-l"
          - "/tests/results.jtl"
          - "-e"
          - "-o"
          - "/tests/report"
        volumeMounts:
        - name: jmeter-tests
          mountPath: /tests
      volumes:
      - name: jmeter-tests
        configMap:
          name: jmeter_pvc
 