apiVersion: apps/v1
kind: Deployment
metadata:
  name: airtrail
  labels:
    app: airtrail
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airtrail
  template:
    metadata:
      labels:
        app: airtrail
    spec:
      containers:
      - name: airtrail
        image: "{{ airtrail_image }}"
        env:
        - name: DATABASE_URL
          value: "{{ db_url }}"
        - name: DB_HOST
          value: "{{ db_host }}"
        - name: DB_URL
          value: "{{ db_url }}"
        - name: DB_DATABASE_NAME
          value: "{{ db_name }}"
        - name: DB_USERNAME
          value: "{{ db_username }}"
        - name: DB_PASSWORD
          value: "{{ db_password }}"
        ports:
        - containerPort: 3000

