apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: airtrail-hpa
  namespace: default
spec:
  minReplicas: {{ hpa_min_replicas | default(1) }}
  maxReplicas: {{ hpa_max_replicas | default(10) }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: airtrail
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ hpa_cpu_target | default(75) }}
