apiVersion: v1
kind: Service
metadata:
  name: airtrail-service
  labels:
    app: airtrail
  namespace: default
spec:
  type: LoadBalancer # Makes the service accessible on a static port on each Node in the cluster.
  selector:
    app: airtrail
{% if session_affinity_enabled %}
  sessionAffinity: ClientIP 
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 7200
{% endif %}
  ports:
    # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - targetPort: 3000 # port that containers are listening on
      port: 3000 # port exposed internally in the cluster
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30007 # a static port assigned on each the node