apiVersion: apps/v1
kind: Deployment
metadata:
  name: airtrail
  labels:
    app: airtrail
  namespace: default
spec:
  replicas: {{ initial_replicas | default(1) }}
  selector:
    matchLabels:
      app: airtrail
  template:
    metadata:
      labels:
        app: airtrail
    spec:
      containers:
      - name: airtrail
        image: "{{ airtrail_image }}"
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: airtrail-secret
              key: database-url
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: airtrail-secret
              key: db-host
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: airtrail-secret
              key: database-url
        - name: DB_DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: airtrail-secret
              key: db-name
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: airtrail-secret
              key: db-username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: airtrail-secret
              key: db-password
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: {{ cpu_request | default('150m') }}
            memory: {{ memory_request | default('256Mi') }}
          limits:
            cpu: {{ cpu_limit | default('500m') }}
            memory: {{ memory_limit | default('512Mi') }}

