---
vm: vm0

vm_template: ascn-template-1

load_vm_zone: us-central1-a

template_region: us-central1

vm_machine_type: e2-standard-4

vm_image_family: debian-12

vm_image_project: debian-cloud

vm_ssh_user: ansible